trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform
  jobs:
  - job: Terraform
    continueOnError: false
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        backendServiceArm: 'Demos (f8b9b693-fc66-4e1b-a547-110404abc3c3)'
        backendAzureRmResourceGroupName: 'terraform'
        backendAzureRmStorageAccountName: 'sapstorage2802'
        backendAzureRmContainerName: 'kkjkkj'
        backendAzureRmKey: 'terraformstate'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        command: 'plan'
        environmentServiceNameAzureRM: 'Demos (f8b9b693-fc66-4e1b-a547-110404abc3c3)'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        command: 'apply'
        environmentServiceNameAzureRM: 'Demos (f8b9b693-fc66-4e1b-a547-110404abc3c3)'

- stage:
  jobs:
   - deployment: RemoveAllResources
     displayName: Remove all resources
     pool:
         vmImage: 'ubuntu-latest'
     environment: 'prod'      
     strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: TerraformTaskV4@4
              inputs:
                provider: 'azurerm'
                command: 'destroy'
                workingDirectory: '$(System.DefaultWorkingDirectory)'
                environmentServiceNameAzureRM: 'Demos (f8b9b693-fc66-4e1b-a547-110404abc3c3)'

    